swagger: "2.0"
info:
  title: "Bulk Roaming Management API"
  description: "API para gestionar el estado, consumo y obtención de status de roaming a granel."
  version: "1.0.0"
host: "your-server-url.com"
basePath: "/mfp/api/adapters/CL_RoamingGranelManagementAdapter_JAuthV3"
schemes:
  - "https"
paths:
  /resource/BulkRoamingChangeStatus:
    post:
      summary: "Cambiar el estado del roaming a granel"
      description: "Cambia el estado del roaming a granel para un suscriptor específico."
      operationId: "bulkRoamingChangeStatus"
      parameters:
        - name: "SubscriberId"
          in: "query"
          required: true
          type: "string"
          description: "MSISDN para activar o desactivar Roaming Datos a Granel."
        - name: "ChannelId"
          in: "query"
          required: true
          type: "string"
          description: "Canal de la solicitud (por ejemplo, '6' para APP)."
        - name: "Action"
          in: "query"
          required: true
          type: "string"
          description: "Acción a ejecutar ('activar' o 'desactivar')."
      responses:
        200:
          description: "Respuesta exitosa"
          schema:
            type: "object"
            properties:
              isSuccessful:
                type: "boolean"
              BulkRoamingChangeStatusResponse:
                type: "object"
                properties:
                  newStatusDescription:
                    type: "string"
                  newStatusId:
                    type: "string"
        400:
          description: "Respuesta de error"
          schema:
            type: "object"
            properties:
              isSuccessful:
                type: "boolean"
              BulkRoamingGetStatusResponse:
                type: "object"
                properties:
                  responseDate:
                    type: "string"
                    format: "date-time"
                  latency:
                    type: "integer"
                  errorList:
                    type: "object"
                    properties:
                      error:
                        type: "array"
                        items:
                          type: "object"
                          properties:
                            code:
                              type: "string"
                            severityLevel:
                              type: "string"
                            description:
                              type: "string"
  /resource/BulkRoamingGetConsumption:
    post:
      summary: "Obtener el consumo del roaming a granel"
      description: "Obtiene la cuota y los consumos de roaming a granel para un suscriptor específico."
      operationId: "bulkRoamingGetConsumption"
      parameters:
        - name: "SubscriberId"
          in: "query"
          required: true
          type: "string"
          description: "MSISDN para obtener la cuota y consumos de Roaming Datos a Granel."
        - name: "ChannelId"
          in: "query"
          required: true
          type: "string"
          description: "Canal de la solicitud (por ejemplo, '6' para APP)."
      responses:
        200:
          description: "Respuesta exitosa"
          schema:
            type: "object"
            properties:
              isSuccessful:
                type: "boolean"
              BulkRoamingGetConsumptionResponse:
                type: "object"
                properties:
                  consumptions:
                    type: "array"
                    items:
                      type: "object"
                      properties:
                        usageUnit:
                          type: "string"
                        description:
                          type: "string"
                        usageQuantity:
                          type: "number"
                        id:
                          type: "string"
                        quotaQuantity:
                          type: "number"
                        quotaUnit:
                          type: "string"
        400:
          description: "Respuesta de error"
          schema:
            type: "object"
            properties:
              isSuccessful:
                type: "boolean"
              BulkRoamingGetConsumptionResponse:
                type: "object"
                properties:
                  responseDate:
                    type: "string"
                    format: "date-time"
                  latency:
                    type: "integer"
                  errorList:
                    type: "object"
                    properties:
                      error:
                        type: "array"
                        items:
                          type: "object"
                          properties:
                            code:
                              type: "string"
                            severityLevel:
                              type: "string"
                            description:
                              type: "string"
  /resource/BulkRoamingGetStatus:
    post:
      summary: "Obtener el estado del roaming a granel"
      description: "Obtiene el estado del roaming a granel para un suscriptor específico."
      operationId: "bulkRoamingGetStatus"
      parameters:
        - name: "SubscriberId"
          in: "query"
          required: true
          type: "string"
          description: "MSISDN para obtener el estado de Roaming Datos a Granel."
        - name: "ChannelId"
          in: "query"
          required: true
          type: "string"
          description: "Canal de la solicitud (por ejemplo, '6' para APP)."
      responses:
        200:
          description: "Respuesta exitosa"
          schema:
            type: "object"
            properties:
              isSuccessful:
                type: "boolean"
              BulkRoamingGetStatusResponse:
                type: "object"
                properties:
                  statusDescription:
                    type: "string"
                  statusId:
                    type: "string"
                  roamingTypeDescription:
                    type: "string"
                  roamingTypeId:
                    type: "string"
        400:
          description: "Respuesta de error"
          schema:
            type: "object"
            properties:
              isSuccessful:
                type: "boolean"
              BulkRoamingGetStatusResponse:
                type: "object"
                properties:
                  responseDate:
                    type: "string"
                    format: "date-time"
                  latency:
                    type: "integer"
                  errorList:
                    type: "object"
                    properties:
                      error:
                        type: "array"
                        items:
                          type: "object"
                          properties:
                            code:
                              type: "string"
                            severityLevel:
                              type: "string"
                            description:
                              type: "string"
